- name: Wait for instances to listen on port 22
  local_action: wait_for state=started host={{ inventory_hostname }} port=22 timeout=150 delay=15

- name: Fix .ssh/known_hosts.
  local_action: command  ssh-keygen -f ~/.ssh/known_hosts -R {{ item }}
  run_once: True
  with_items: "{{ play_hosts }}"

- name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
  local_action: command sh -c 'ssh-keyscan -H {{ item }} >>$HOME/.ssh/known_hosts'
  run_once: True
  with_items: "{{ play_hosts }}"

- name: install python 2
  raw: bash -c "test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)"
  sudo: true

- name: Fix 'Could not load host key /etc/ssh/ssh_host_ed25519_key'
  shell: 'ssh-keygen -A'
  become: true

- name: update /etc/hosts
  lineinfile: >
      dest=/etc/hosts
      line="{{ ansible_eth0['ipv4']['address'] }} {{ hostname }}"
      regexp="^{{ ansible_eth0['ipv4']['address'] }}"
  become: true

- name: "set hostname"
  hostname: name="{{ hostname }}"
  become: true

